PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX base: <http://w3id.org/foodie/lucas/lcvalue>
PREFIX sosa:  <http://www.w3.org/ns/sosa/> 
PREFIX owl:   <http://www.w3.org/2002/07/owl#> 
PREFIX glosis_cm: <http://w3id.org/glosis/model/common#>
PREFIX glosis_lh: <http://w3id.org/glosis/model/layerhorizon#> 
PREFIX glosis_cl: <http://w3id.org/glosis/model/codelists#> 
PREFIX glosis_sp: <http://w3id.org/glosis/model/siteplot#> 
PREFIX glosis_pr: <http://w3id.org/glosis/model/profile#> 
PREFIX iso19103: <http://def.seegrid.csiro.au/isotc211/iso19103/2005/basic#> 
PREFIX iso28258: 	<http://w3id.org/glosis/model/iso28258/2013#> 
PREFIX qudt: <http://qudt.org/schema/qudt/> 
PREFIX unit: <http://qudt.org/vocab/unit/> 
PREFIX sosa:  <http://www.w3.org/ns/sosa/> 
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX oim-jf: <https://w3id.org/iliad/oim/jellyfish>
PREFIX wgs84: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>
PREFIX oim-jf: <http://w3id.org/iliad/oim/jellyfish#>
PREFIX dwc-mbg: <http://mmisw.org/ont/ioos/marine_biogeography/>
PREFIX s4watr: <https://saref.etsi.org/saref4watr/>
PREFIX m3-lite: <http://purl.org/iot/vocab/m3-lite#>
PREFIX schema: <https://schema.org/>
PREFIX waterp: <http://w3id.org/ad4gd/model/ext/water/>


### observation collection
CONSTRUCT {
  ?obs_col_URI a sosa:ObservationCollection ;
  	rdfs:label ?obs_col_label ;
	sosa:observedProperty ?property_URI ;
	sosa:madeBySensor ?sensor_URI ;
	sosa:usedProcedure ?procedure_URI ;	
	sosa:hasFeatureOfInterest ?feature_URI ;
	sosa:hasMember ?obs_URI ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {		
	BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot/water/level/observationCol/',str(?Stationsnummer))) AS ?obs_col_URI)
	BIND (STRLANG(CONCAT('Monthly mean water for lake: ',?Gewsser,' station: ', str(?Stationsnummer)),"en") AS ?obs_col_label)	
	BIND (URI('http://w3id.org/ad4gd/model/ext/water/waterLevel') AS ?property_URI)
	BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot/water/level/sensor/',str(?Stationsnummer))) AS ?sensor_URI)
	BIND (URI('http://w3id.org/ad4gd/pilot/water/level/procedure') AS ?procedure_URI)	  
	BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot/water/level/feature/', STR(?Gewsser))) AS ?feature_URI)
	BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot/water/level/observation/',str(?Stationsnummer),'/',str(?Jahr),'/',str(?Monat))) AS ?obs_URI)  
}

### observation 
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:phenomenonTime ?propert_date ; 
  	sosa:resultTime ?propert_date ;
  	sosa:hasResult ?results_URI ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
  BIND (strdt(concat(?Jahr,'-',if(?Monat='Januar','01',if(?Monat='Februar','02',if(?Monat='Mrz','03',if(?Monat='April','04',if(?Monat='Mai','05',if(?Monat='Juni','06',if(?Monat='Juli','07',if(?Monat='August','08',if(?Monat='September','09',if(?Monat='Oktober','10',if(?Monat='November','11',if(?Monat='Dezember','12','01')))))))))))),'-01','T00:00:00'),xsd:dateTime) AS ?propert_date)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot/water/level/observation/',str(?Stationsnummer),'/',str(?Jahr),'/',str(?Monat))) AS ?obs_URI)  
  BIND (STRLANG(CONCAT('Monthly mean water for lake: ',?Gewsser,' station: ', ?Stationsnummer,' year: ',?Jahr,' month: ',?Monat),"en") AS ?obs_label)	    	 
  BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot/water/level/observation/',str(?Stationsnummer),'/',str(?Jahr),'/',str(?Monat),'/result')) AS ?results_URI)  
}	

### feature of interest
CONSTRUCT {
  ?feature_URI a sosa:FeatureOfInterest, s4watr:Lake ;
  	rdfs:label ?feature_label ;
  	wgs84:lat ?Lat ;
  	wgs84:long ?lon ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
  BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot/water/level/feature/', STR(?Gewsser))) AS ?feature_URI)    
  BIND (STRLANG(CONCAT('Feature of interest - lake: ', STR(?Gewsser)),"en") AS ?feature_label)
}

### observed property
CONSTRUCT {
  ?property_URI a sosa:ObservableProperty ;
  	rdfs:label ?property_label ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
  BIND (URI('http://w3id.org/ad4gd/model/ext/water/waterLevel') AS ?property_URI)
  BIND (STRLANG('Water level',"en") AS ?property_label)
}


### simulation sensor
CONSTRUCT {
  ?sensor_URI a sosa:Sensor , s4watr:GaugingStation;
  	rdfs:label ?sensor_label ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
  BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot/water/level/sensor/',str(?Stationsnummer))) AS ?sensor_URI)
  BIND (STRLANG(CONCAT('Station: ', STR(?Stationsnummer),' name: ',str(?Stationsname)),"en") AS ?sensor_label)
}

###  procedure 
CONSTRUCT {
  ?procedure_URI a sosa:Procedure ;
  	rdfs:label ?procedure_label ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
  BIND (URI('http://w3id.org/ad4gd/pilot/water/level/procedure') AS ?procedure_URI)	  
  BIND (STRLANG('Collection of raw data from stations',"en") AS ?procedure_label)
}

### observation result
CONSTRUCT {
  ?results_URI a sosa:Result, m3-lite:WaterLevel ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?Monatsmittelwert ;
	qudt:unit ?uom ;
	schema:minValue ?Monatsminimum ; 
	schema:maxValue ?Monatsmaximum ;
  waterp:minValueDate ?ZeitpunktMinimum ;
	waterp:maxValueDate ?ZeitpunktMaximum ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
  BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot/water/level/observation/',str(?Stationsnummer),'/',str(?Jahr),'/',str(?Monat),'/result')) AS ?results_URI)  
  BIND (STRLANG(CONCAT('Result of monthly mean water for lake: ',?Gewsser,' station: ', ?Stationsnummer,' year: ',?Jahr,' month: ',?Monat),"en") AS ?result_label)
  BIND (URI('http://qudt.org/vocab/unit/CentiM') AS ?uom))
}