PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX base: <http://w3id.org/foodie/lucas/lcvalue>
PREFIX sosa:  <http://www.w3.org/ns/sosa/> 
PREFIX owl:   <http://www.w3.org/2002/07/owl#> 
PREFIX glosis_cm: <http://w3id.org/glosis/model/common#>
PREFIX glosis_lh: <http://w3id.org/glosis/model/layerhorizon#> 
PREFIX glosis_cl: <http://w3id.org/glosis/model/codelists#> 
PREFIX glosis_sp: <http://w3id.org/glosis/model/siteplot#> 
PREFIX glosis_pr: <http://w3id.org/glosis/model/profile#> 
PREFIX iso19103: <http://def.seegrid.csiro.au/isotc211/iso19103/2005/basic#> 
PREFIX iso28258: 	<http://w3id.org/glosis/model/iso28258/2013#> 
PREFIX qudt: <http://qudt.org/schema/qudt/> 
PREFIX unit: <http://qudt.org/vocab/unit/> 
PREFIX sosa:  <http://www.w3.org/ns/sosa/> 
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX oim-jf: <https://w3id.org/iliad/oim/jellyfish>
PREFIX wgs84: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>
PREFIX oim-jf: <http://w3id.org/iliad/oim/jellyfish#>
PREFIX dwc-mbg: <http://mmisw.org/ont/ioos/marine_biogeography/>


### observation collection
CONSTRUCT {
  ?obs_col_URI a sosa:ObservationCollection ;
  	rdfs:label ?obs_col_label ;
    dct:identifier ?ident ;
    sosa:madeBySensor ?sensor_URI ;
    sosa:hasFeatureOfInterest ?feature_URI ;
    sosa:phenomenonTime ?timestamp_prop ; 
  	sosa:resultTime ?timestamp_prop ;

	
		
	sosa:hasMember ?obs_URI1 ;
	sosa:hasMember ?obs_URI2 ;
	sosa:hasMember ?obs_URI3 ;
	sosa:hasMember ?obs_URI4 ;
	sosa:hasMember ?obs_URI5 ;
	sosa:hasMember ?obs_URI6 ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {		
	BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observationCollection/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_col_URI)
	BIND (STRLANG(CONCAT('Sensor community observation collection on: ', STR(?timestamp), ' for sensor: ', STR(?sensor_id),' at location id: ',STR(?location)),"en") AS ?obs_col_label)	    	 
    BIND (CONCAT(STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location)) AS ?ident)	
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/sensor/',STR(?sensor_id))) AS ?sensor_URI)
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/location/',STR(?location))) AS ?feature_URI)
    BIND (xsd:dateTime(?timestamp) AS ?timestamp_prop)	  			
	
	BIND (IF(BOUND(?P1), URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm1.0/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))), ?nothing) AS ?obs_URI1)
    BIND (IF(BOUND(?P2), URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm2.5/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))), ?nothing) AS ?obs_URI2)    
    BIND (IF(BOUND(?pressure), URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pressure/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))), ?nothing) AS ?obs_URI3)
    BIND (IF(BOUND(?pressure_sealevel), URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pressure_sealevel/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))), ?nothing) AS ?obs_URI4)
    BIND (IF(BOUND(?temperature), URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/temperature/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))), ?nothing) AS ?obs_URI5)
    BIND (IF(BOUND(?humidity), URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/humidity/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))), ?nothing) AS ?obs_URI6)
    BIND (IF(BOUND(?P0), URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm10/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))), ?nothing) AS ?obs_URI7)    
}


### observation 1
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;
    dct:identifier ?ident ;
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
    sosa:usedProcedure ?proc_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
    FILTER (BOUND(?P1))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm1.0/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_URI)
    BIND (STRLANG(CONCAT('Sensor community observation on: ',STR(?timestamp),' for sensor: ',STR(?sensor_id),' at location id: ',STR(?location),' for property: PM1.0'),"en") AS ?obs_label)	    	 
    BIND (CONCAT('pm1.0-',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location)) AS ?ident)	
    BIND (URI('https://w3id.org/ad4gd/air-quality/properties/pm1.0') AS ?property_URI)
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm1.0/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)
    BIND (URI('https://w3id.org/ad4gd/air-quality/procedures/pm-humidity-correction') AS ?proc_URI)  
}

### observation 2
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ; 
    dct:identifier ?ident ; 	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
    sosa:usedProcedure ?proc_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
    FILTER (BOUND(?P2))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm2.5/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_URI)
    BIND (STRLANG(CONCAT('Sensor community observation on: ',STR(?timestamp),' for sensor: ',STR(?sensor_id),' at location id: ',STR(?location),' for property: PM2.5'),"en") AS ?obs_label)
    BIND (CONCAT('pm2.5-',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location)) AS ?ident)	
    BIND (URI('https://w3id.org/ad4gd/air-quality/properties/pm2.5') AS ?property_URI)    
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm2.5/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)
    BIND (URI('https://w3id.org/ad4gd/air-quality/procedures/pm-humidity-correction') AS ?proc_URI)  
}

### observation 3
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  
    dct:identifier ?ident ; 		
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?pressure))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pressure/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_URI)    
    BIND (STRLANG(CONCAT('Sensor community observation on: ',STR(?timestamp),' for sensor: ',STR(?sensor_id),' at location id: ',STR(?location),' for property: pressure'),"en") AS ?obs_label)    
    BIND (CONCAT('pressure-',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location)) AS ?ident)
    BIND (URI('https://w3id.org/ad4gd/air-quality/properties/pressure') AS ?property_URI)
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pressure/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)    
}

### observation 4
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
    dct:identifier ?ident ;
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?pressure_sealevel))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pressure_sealevel/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_URI)    
    BIND (STRLANG(CONCAT('Sensor community observation on: ',STR(?timestamp),' for sensor: ',STR(?sensor_id),' at location id: ',STR(?location),' for property: pressure_sealevel'),"en") AS ?obs_label)    
    BIND (CONCAT('pressure_sealevel-',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location)) AS ?ident)
    BIND (URI('https://w3id.org/ad4gd/air-quality/properties/pressure') AS ?property_URI)
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pressure_sealevel/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)      
}

### observation 5
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  
    dct:identifier ?ident ;	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?temperature))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/temperature/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_URI)    
    BIND (STRLANG(CONCAT('Sensor community observation on: ',STR(?timestamp),' for sensor: ',STR(?sensor_id),' at location id: ',STR(?location),' for property: temperature'),"en") AS ?obs_label)    
    BIND (CONCAT('temperature-',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location)) AS ?ident)
    BIND (URI('https://w3id.org/ad4gd/air-quality/properties/temperature') AS ?property_URI)
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/temperature/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)        
}

### observation 6
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  
    dct:identifier ?ident ;	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?humidity))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/humidity/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_URI)    
    BIND (STRLANG(CONCAT('Sensor community observation on: ',STR(?timestamp),' for sensor: ',STR(?sensor_id),' at location id: ',STR(?location),' for property: humidity'),"en") AS ?obs_label)    
    BIND (CONCAT('humidity-',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location)) AS ?ident)
    BIND (URI('https://w3id.org/ad4gd/air-quality/properties/humidity') AS ?property_URI)
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/humidity/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)          
}

### observation 7
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  
    dct:identifier ?ident ;	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
    sosa:usedProcedure ?proc_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?P0))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm10/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_URI)        
    BIND (STRLANG(CONCAT('Sensor community observation on: ',STR(?timestamp),' for sensor: ',STR(?sensor_id),' at location id: ',STR(?location),' for property: pm10'),"en") AS ?obs_label)    
    BIND (CONCAT('pm10-',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location)) AS ?ident)
    BIND (URI('https://w3id.org/ad4gd/air-quality/properties/pm10') AS ?property_URI)
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm10/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)          
    BIND (URI('https://w3id.org/ad4gd/air-quality/procedures/pm-humidity-correction') AS ?proc_URI)  
}


### feature of interest
CONSTRUCT {
  ?feature_URI a sosa:FeatureOfInterest, wgs84:Point , dct:Location ;
  	rdfs:label ?feature_label ;
    dct:identifier ?ident ;	
  	wgs84:lat ?lat ;
  	wgs84:long ?lon ;
    wgs84:alt ?altitude ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/location/',STR(?location))) AS ?feature_URI)    
    BIND (STRLANG(CONCAT('Feature of interest with location id:', STR(?location)),"en") AS ?feature_label)
    BIND (CONCAT('location-',STR(?location)) AS ?ident)
}

### observed property pm1
CONSTRUCT {
  ?property_URI a sosa:ObservableProperty ;
  	rdfs:label ?property_label ;
    dct:identifier ?ident ;	
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
    FILTER (BOUND(?P1))
    BIND (URI('https://w3id.org/ad4gd/air-quality/properties/pm1.0') AS ?property_URI)
    BIND (STRLANG('Particulate matter < 1 µm',"en") AS ?property_label)
    BIND ('ad4gd-pm1.0' AS ?ident)
}

### observed property pm25
 CONSTRUCT {
   ?property_URI a sosa:ObservableProperty ;
   	rdfs:label ?property_label ;
    dct:identifier ?ident ;	
 }  	
 FROM <file:pereira_comcom_id31_20220321_v2.csv> 
 WHERE {
   FILTER (BOUND(?P2))
   BIND (URI('https://w3id.org/ad4gd/air-quality/properties/pm2.5') AS ?property_URI)
   BIND (STRLANG('Particulate matter < 2.5 µm',"en") AS ?property_label)
   BIND ('ad4gd-pm2.5' AS ?ident)
 }

### observed property pressure
 CONSTRUCT {
     ?property_URI a sosa:ObservableProperty ;
   	rdfs:label ?property_label ;
    dct:identifier ?ident ;	
 }  	
 FROM <file:pereira_comcom_id31_20220321_v2.csv> 
 WHERE {
     FILTER (BOUND(?pressure))
     BIND (URI('https://w3id.org/ad4gd/air-quality/properties/pressure') AS ?property_URI)
     BIND (STRLANG('Air Pressure',"en") AS ?property_label)
     BIND ('ad4gd-pressure' AS ?ident)
 }

### observed property pressure_sealevel
 CONSTRUCT {
     ?property_URI a sosa:ObservableProperty ;
   	rdfs:label ?property_label ;
    dct:identifier ?ident ;	
 }  	
 FROM <file:pereira_comcom_id31_20220321_v2.csv> 
 WHERE {
     FILTER (BOUND(?pressure_sealevel))
     BIND (URI('https://w3id.org/ad4gd/air-quality/properties/pressureSeaLevel') AS ?property_URI) ## no exissts
     BIND (STRLANG('Air Pressure at sea level',"en") AS ?property_label)
     BIND ('ad4gd-pressure-sealevel' AS ?ident)
 }

### observed property temperature
 CONSTRUCT {
   ?property_URI a sosa:ObservableProperty ;
   	rdfs:label ?property_label ;
    dct:identifier ?ident ;	
 }  	
 FROM <file:pereira_comcom_id31_20220321_v2.csv> 
 WHERE {
     FILTER (BOUND(?temperature))
     BIND (URI('https://w3id.org/ad4gd/air-quality/properties/temperature') AS ?property_URI)
     BIND (STRLANG('Air Temperature',"en") AS ?property_label)
     BIND ('ad4gd-temperature' AS ?ident)
 }

### observed property humidity
 CONSTRUCT {
   ?property_URI a sosa:ObservableProperty ;
   	rdfs:label ?property_label ;
    dct:identifier ?ident ;	
 }  	
 FROM <file:pereira_comcom_id31_20220321_v2.csv> 
 WHERE {
     FILTER (BOUND(?humidity))
     BIND (URI('https://w3id.org/ad4gd/air-quality/properties/humidity') AS ?property_URI)
     BIND (STRLANG('Air Humidity',"en") AS ?property_label)
     BIND ('ad4gd-humidity' AS ?ident)
 }

### observed property pm10
 CONSTRUCT {
   ?property_URI a sosa:ObservableProperty ;
   	rdfs:label ?property_label ;
    dct:identifier ?ident ;	
 }  	
 FROM <file:pereira_comcom_id31_20220321_v2.csv> 
 WHERE {
     FILTER (BOUND(?P0))
     BIND (URI('https://w3id.org/ad4gd/air-quality/properties/pm10') AS ?property_URI)
     BIND (STRLANG('Particulate matter < 10 µm',"en") AS ?property_label)
     BIND ('ad4gd-pm10' AS ?ident)
 } 

### simulation sensor
CONSTRUCT {
  ?sensor_URI a sosa:Sensor ;
    rdfs:label ?sensor_label ;
    dct:identifier ?ident ;
    dct:type ?sensor_type_url ;  
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {    
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/sensor/',STR(?sensor_id))) AS ?sensor_URI)
    BIND (STRLANG(CONCAT('Sensor: ',STR(?sensor_id),' type: ',STR(?sensor_type)),"en") AS ?sensor_label)
    BIND (CONCAT('sensor-',STR(?sensor_id)) AS ?ident)
    BIND (URI(CONCAT('https://w3id.org/ad4gd/air-quality/sensors/',STR(?sensor_type))) AS ?sensor_type_url)
}

### simulation sensor type
CONSTRUCT {
  ?sensor_type_url a skos:Concept ;
    rdfs:label ?label ;        
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
    BIND (URI(CONCAT('https://w3id.org/ad4gd/air-quality/sensors/',STR(?sensor_type))) AS ?sensor_type_url)
    BIND (STR(?sensor_type) AS ?label)  
}


###  procedure 
CONSTRUCT {
  ?procedure_URI a sosa:Procedure ;
  	rdfs:label ?procedure_label ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
  BIND (URI('https://w3id.org/ad4gd/air-quality/procedures/pm-humidity-correction') AS ?location_URI)
  BIND (STRLANG('Humidity correction for Particulate Matter',"en") AS ?procedure_label)
}

### observation result 1
CONSTRUCT {
  ?obs_result_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?P1 ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?P1))    
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm1.0/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)
    BIND (STRLANG(CONCAT(STR(?P1),' ug/m3'),"en") AS ?result_label)	    	 
    BIND (URI('http://qudt.org/vocab/unit/MicroGM-PER-M3') AS ?uom)
}

### observation result 2
CONSTRUCT {
  ?obs_result_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?P2 ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?P2))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm2.5/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)
    BIND (STRLANG(CONCAT(STR(?P2),' ug/m3'),"en") AS ?result_label)	    	 
    BIND (URI('http://qudt.org/vocab/unit/MicroGM-PER-M3') AS ?uom)    
}

### observation result 3
CONSTRUCT {
  ?obs_result_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?pressure ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?pressure))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pressure/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)
    BIND (STRLANG(CONCAT(STR(?pressure),' Pa'),"en") AS ?result_label)	    	 
    BIND (URI('http://qudt.org/vocab/unit/PA') AS ?uom)     
}

### observation result 4
CONSTRUCT {
  ?obs_result_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?pressure_sealevel ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?pressure_sealevel))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pressure_sealevel/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)
    BIND (STRLANG(CONCAT(STR(?pressure_sealevel),' Pa'),"en") AS ?result_label)	    	 
    BIND (URI('http://qudt.org/vocab/unit/PA') AS ?uom)         
}

### observation result 5
CONSTRUCT {
  ?obs_result_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?temperature ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?temperature))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/temperature/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)
    BIND (STRLANG(CONCAT(STR(?temperature),' °C'),"en") AS ?result_label)	    	 
    BIND (URI('http://qudt.org/vocab/unit/DEG_C') AS ?uom)             
}

### observation result 6
CONSTRUCT {
  ?obs_result_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?humidity ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?humidity))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/humidity/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)
    BIND (STRLANG(CONCAT(STR(?humidity),' %RH'),"en") AS ?result_label)	    	 
    BIND (URI('http://qudt.org/vocab/unit/PERCENT_RH') AS ?uom)                 
}

### observation result 7
CONSTRUCT {
  ?obs_result_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?P0 ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?P0))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/pilot3/airquality/sensorcommunity/observation/pm10/result/',STR(?timestamp),'-',STR(?sensor_id),'-',STR(?location))) AS ?obs_result_URI)              
    BIND (STRLANG(CONCAT(STR(?P0),' ug/m3'),"en") AS ?result_label)	    	 
    BIND (URI('http://qudt.org/vocab/unit/MicroGM-PER-M3') AS ?uom)                 
}