PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX base: <http://w3id.org/foodie/lucas/lcvalue>
PREFIX sosa:  <http://www.w3.org/ns/sosa/> 
PREFIX owl:   <http://www.w3.org/2002/07/owl#> 
PREFIX glosis_cm: <http://w3id.org/glosis/model/common#>
PREFIX glosis_lh: <http://w3id.org/glosis/model/layerhorizon#> 
PREFIX glosis_cl: <http://w3id.org/glosis/model/codelists#> 
PREFIX glosis_sp: <http://w3id.org/glosis/model/siteplot#> 
PREFIX glosis_pr: <http://w3id.org/glosis/model/profile#> 
PREFIX iso19103: <http://def.seegrid.csiro.au/isotc211/iso19103/2005/basic#> 
PREFIX iso28258: 	<http://w3id.org/glosis/model/iso28258/2013#> 
PREFIX qudt: <http://qudt.org/schema/qudt/> 
PREFIX unit: <http://qudt.org/vocab/unit/> 
PREFIX sosa:  <http://www.w3.org/ns/sosa/> 
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX oim-jf: <https://w3id.org/iliad/oim/jellyfish>
PREFIX wgs84: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>
PREFIX oim-jf: <http://w3id.org/iliad/oim/jellyfish#>
PREFIX dwc-mbg: <http://mmisw.org/ont/ioos/marine_biogeography/>


### observation collection
CONSTRUCT {
  ?obs_col_URI a sosa:ObservationCollection ;
  rdfs:label ?obs_col_label ;
	sosa:madeBySensor ?sensor_URI ;
	sosa:hasFeatureOfInterest ?feature_URI ;
	sosa:phenomenonTime ?timestamp_prop ; 
  sosa:resultTime ?timestamp_prop ;
	sosa:usedProcedure ?procedure_URI ;	
	sosa:hasMember ?obs_URI1 ;
	sosa:hasMember ?obs_URI2 ;
	sosa:hasMember ?obs_URI3 ;
	sosa:hasMember ?obs_URI4 ;
	sosa:hasMember ?obs_URI5 ;
	sosa:hasMember ?obs_URI6 ;
  sosa:hasMember ?obs_URI7 ;
  sosa:hasMember ?obs_URI8 ;
  sosa:hasMember ?obs_URI9 ;
  sosa:hasMember ?obs_URI10 ;
  sosa:hasMember ?obs_URI11 ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {		
	BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM))) AS ?obs_col_URI)
	BIND (STRLANG(CONCAT('Sensor community observation collection: ', ' location: ',STR("Aston University"),' time: ',STR(?Timestamp_Local)),"en") AS ?obs_col_label)	    	 
	BIND (URI('http://w3id.org/ad4gd/airquality/zephyr/sensor') AS ?sensor_URI)
	BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/location/', "astonUniversity")) AS ?feature_URI)
    BIND (STRDT(?TimestampUTC, xsd:dateTime) AS ?timestamp_prop)  
    #BIND (STRDT(?Timestamp_Local_, xsd:dateTime) AS ?timestamp_prop1)  
	BIND (URI('http://w3id.org/ad4gd/airquality/zephyr/procedure/sensing') AS ?procedure_URI)
	
    BIND (IF(BOUND(?814_TempC_slotB), URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/temperature')), ?nothing) AS ?obs_URI1)
    BIND (IF(BOUND(?814_HumidityRH_slotB), URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/humidity')), ?nothing) AS ?obs_URI2)
    BIND (IF(BOUND(?814_NO2ugm3_slotB), URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/no2')), ?nothing) AS ?obs_URI3)
    BIND (IF(BOUND(?814_O3ugm3_slotB), URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/03')), ?nothing) AS ?obs_URI4)
    BIND (IF(BOUND(?814_NOugm3_slotB), URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/no')), ?nothing) AS ?obs_URI5)
    BIND (IF(BOUND(?814_PM1ugm3_slotB), URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/pm1')), ?nothing) AS ?obs_URI6)
    BIND (IF(BOUND(?814_PM25ugm3_slotB), URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/pm25')), ?nothing) AS ?obs_URI7)
    BIND (IF(BOUND(?814_PM10ugm3_slotB), URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/pm10')), ?nothing) AS ?obs_URI8)
    BIND (IF(BOUND(?814_Ambient_tempC_slotB), URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/ambientTemperature')), ?nothing) AS ?obs_URI9)
    BIND (IF(BOUND(?814_Ambient_humidityRH_slotB), URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/ambientHumidity')), ?nothing) AS ?obs_URI10)
    BIND (IF(BOUND(?814_Ambient_pressurehPa_slotB), URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/ambientPressure')), ?nothing) AS ?obs_URI11)
}


### observation 1
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?814_TempC_slotB))
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/temperature')) AS ?obs_URI)
  BIND (STRLANG(CONCAT('Sensor community observation collection: ',STR(?sensor_id),' location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: temperature'),"en") AS ?obs_label)	    	 
  BIND (URI('http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/54') AS ?property_URI)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/temperature/result')) AS ?obs_result_URI)
}

### observation 2
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?814_HumidityRH_slotB))
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/humidity')) AS ?obs_URI)
  BIND (STRLANG(CONCAT('Sensor community observation collection: ',STR(?sensor_id),' location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: humidity'),"en") AS ?obs_label)	    	 
  BIND (URI('http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/55') AS ?property_URI)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/humidity/result')) AS ?obs_result_URI)
}

### observation 3
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?814_NO2ugm3_slotB))
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/no2')) AS ?obs_URI)
  BIND (STRLANG(CONCAT('Sensor community observation collection: ',STR(?sensor_id),' location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: no2'),"en") AS ?obs_label)	    	 
  BIND (URI('http://dd.eionet.europa.eu/vocabulary/aq/pollutant/8') AS ?property_URI)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/no2/result')) AS ?obs_result_URI)
}

### observation 4
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?814_O3ugm3_slotB))
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/o3')) AS ?obs_URI)
  BIND (STRLANG(CONCAT('Sensor community observation collection: ',STR(?sensor_id),' location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: o3'),"en") AS ?obs_label)	    	 
  BIND (URI('http://dd.eionet.europa.eu/vocabulary/aq/pollutant/7') AS ?property_URI)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/o3/result')) AS ?obs_result_URI)
}

### observation 5
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?814_NOugm3_slotB))
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/no')) AS ?obs_URI)
  BIND (STRLANG(CONCAT('Sensor community observation collection: ',STR(?sensor_id),' location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: no'),"en") AS ?obs_label)	    	 
  BIND (URI('http://dd.eionet.europa.eu/vocabulary/aq/pollutant/38') AS ?property_URI)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/no/result')) AS ?obs_result_URI)
}

### observation 6
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?814_PM1ugm3_slotB))
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/pm1')) AS ?obs_URI)
  BIND (STRLANG(CONCAT('Sensor community observation collection: ',STR(?sensor_id),' location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: pm1'),"en") AS ?obs_label)	    	 
  BIND (URI('http://dd.eionet.europa.eu/vocabulary/aq/pollutant/6002') AS ?property_URI)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/pm1/result')) AS ?obs_result_URI)
}

### observation 7
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?814_PM25ugm3_slotB))
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/pm25')) AS ?obs_URI)
  BIND (STRLANG(CONCAT('Sensor community observation collection: ',STR(?sensor_id),' location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: pm25'),"en") AS ?obs_label)	    	 
  BIND (URI('http://dd.eionet.europa.eu/vocabulary/aq/pollutant/6001') AS ?property_URI)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/pm25/result')) AS ?obs_result_URI)
}

### observation 8
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?814_PM10ugm3_slotB))
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/pm10')) AS ?obs_URI)
  BIND (STRLANG(CONCAT('Sensor community observation collection: ',STR(?sensor_id),' location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: pm10'),"en") AS ?obs_label)	    	 
  BIND (URI('http://dd.eionet.europa.eu/vocabulary/aq/pollutant/5') AS ?property_URI)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/pm10/result')) AS ?obs_result_URI)
}

### observation 9
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?814_Ambient_tempC_slotB))
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/ambientTemperature')) AS ?obs_URI)
  BIND (STRLANG(CONCAT('Sensor community observation collection: ',STR(?sensor_id),' location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: ambient temperature'),"en") AS ?obs_label)	    	 
  BIND (URI('http://vocab.nerc.ac.uk/collection/P07/current/CFSN0023/') AS ?property_URI)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/ambientTemperature/result')) AS ?obs_result_URI)
}

### observation 10
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?814_Ambient_humidityRH_slotB))
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/ambientHumidity')) AS ?obs_URI)
  BIND (STRLANG(CONCAT('Sensor community observation collection: ',STR(?sensor_id),' location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: ambient humidity'),"en") AS ?obs_label)	    	 
  BIND (URI('http://vocab.nerc.ac.uk/collection/P07/current/CFSN0313/') AS ?property_URI)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/ambientHumidity/result')) AS ?obs_result_URI)
}

### observation 11
CONSTRUCT {
  ?obs_URI a sosa:Observation ;
  	rdfs:label ?obs_label ;  	
  	sosa:observedProperty ?property_URI ;
  	sosa:hasResult ?obs_result_URI ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
	FILTER (BOUND(?814_Ambient_pressurehPa_slotB))
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/ambientPressure')) AS ?obs_URI)
  BIND (STRLANG(CONCAT('Sensor community observation collection: ',STR(?sensor_id),' location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: ambient pressure'),"en") AS ?obs_label)	    	 
  BIND (URI('http://vocab.nerc.ac.uk/collection/P07/current/CFSN0015/') AS ?property_URI)
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/',STR(?ROWNUM),'/observation/ambientPressure/result')) AS ?obs_result_URI)
}

### feature of interest
CONSTRUCT {
  ?feature_URI a sosa:FeatureOfInterest, wgs84:Point , dct:Location ;
  	rdfs:label ?feature_label ;
  	wgs84:lat ?lat ;
  	wgs84:long ?lon ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
  BIND (URI(CONCAT('http://w3id.org/ad4gd/airquality/zephyr/location/', 'astonUniversity')) AS ?feature_URI)
  BIND (STRLANG(CONCAT('Feature of interest: location: ', "Aston University"),"en") AS ?feature_label)
  BIND (xsd:decimal("52.486717") AS ?lat)
  BIND (xsd:decimal("-1.8908227") AS ?lon)
}

### simulation sensor
CONSTRUCT {
  ?sensor_URI a sosa:Sensor ;
  rdfs:label ?sensor_label ;
  dct:type ?sensor_type ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
  BIND (URI('http://w3id.org/ad4gd/airquality/zephyr/sensor') AS ?sensor_URI)
  BIND (STRLANG(CONCAT('Sensor: ', 'Zephyr Air Quality Monitor'),"en") AS ?sensor_label)
}

###  procedure 
CONSTRUCT {
  ?procedure_URI a sosa:Procedure ;
  	rdfs:label ?procedure_label ;
}  	
FROM <file:pereira_comcom_id31_20220321_v2.csv> 
WHERE {
  BIND (URI('http://w3id.org/ad4gd/airquality/zephyr/procedure/sensing') AS ?location_URI)
  BIND (STRLANG('Sensing measurements',"en") AS ?procedure_label)
}

### observation result 1
CONSTRUCT {
  ?results_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?814_TempC_slotB ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?814_TempC_slotB))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/zephyr/sensorcommunity/',STR(?ROWNUM),'/observation/temperature/result')) AS ?results_URI)
    BIND (STRLANG(CONCAT('Result for observation of sensor: location: ','Aston University',' time: ',STR(?Timestamp_Local),'property: temperature'),"en") AS ?result_label)	
    BIND (URI('http://qudt.org/vocab/unit/DEG_C') AS ?uom)
}

### observation result 2
CONSTRUCT {
  ?results_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?814_Humidity__RH__slotB ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?814_HumidityRH_slotB))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/zephyr/sensorcommunity/',STR(?ROWNUM),'/observation/temperature/result')) AS ?results_URI)
    BIND (STRLANG(CONCAT('Result for observation of sensor: location: ','Aston University',' time: ',STR(?TimestampLocal),'property: humidity'),"en") AS ?result_label)	
    BIND (URI('http://qudt.org/vocab/unit/PERCENT_RH') AS ?uom)
}
### observation result 3
CONSTRUCT {
  ?results_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?814_NO2ugm3_slotB ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?814_NO2ugm3_slotB))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/zephyr/sensorcommunity/',STR(?ROWNUM),'/observation/temperature/result')) AS ?results_URI)
    BIND (STRLANG(CONCAT('Result for observation of sensor: location: ','Aston University',' time: ',STR(?TimestampLocal),'property: no2'),"en") AS ?result_label)	
    BIND (URI('http://qudt.org/vocab/unit/MicroGM-PER-M3') AS ?uom)
}
### observation result 4
CONSTRUCT {
  ?results_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?814_O3ugm3_slotB ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?814_O3ugm3_slotB))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/zephyr/sensorcommunity/',STR(?ROWNUM),'/observation/temperature/result')) AS ?results_URI)
    BIND (STRLANG(CONCAT('Result for observation of sensor: location: ','Aston University',' time: ',STR(?TimestampLocal),'property: o3'),"en") AS ?result_label)	
    BIND (URI('http://qudt.org/vocab/unit/MicroGM-PER-M3') AS ?uom)
}
### observation result 5
CONSTRUCT {
  ?results_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?814_NOugm3_slotB ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?814_NOugm3_slotB))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/zephyr/sensorcommunity/',STR(?ROWNUM),'/observation/temperature/result')) AS ?results_URI)
    BIND (STRLANG(CONCAT('Result for observation of sensor: location: ','Aston University',' time: ',STR(?TimestampLocal),'property: no'),"en") AS ?result_label)	
    BIND (URI('http://qudt.org/vocab/unit/MicroGM-PER-M3') AS ?uom)
}
### observation result 6
CONSTRUCT {
  ?results_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?814_PM1ugm3_slotB ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?814_PM1ugm3_slotB))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/zephyr/sensorcommunity/',STR(?ROWNUM),'/observation/temperature/result')) AS ?results_URI)
    BIND (STRLANG(CONCAT('Result for observation of sensor: location: ','Aston University',' time: ',STR(?TimestampLocal),'property: pm1'),"en") AS ?result_label)	
    BIND (URI('http://qudt.org/vocab/unit/MicroGM-PER-M3') AS ?uom)
}
### observation result 7
CONSTRUCT {
  ?results_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?814_PM25ugm3_slotB ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?814_PM25ugm3_slotB))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/zephyr/sensorcommunity/',STR(?ROWNUM),'/observation/temperature/result')) AS ?results_URI)
    BIND (STRLANG(CONCAT('Result for observation of sensor: location: ','Aston University',' time: ',STR(?TimestampLocal),'property: pm2'),"en") AS ?result_label)	
    BIND (URI('http://qudt.org/vocab/unit/MicroGM-PER-M3') AS ?uom)
}
### observation result 8
CONSTRUCT {
  ?results_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?814_PM10ugm3_slotB ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?814_PM10ugm3_slotB))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/zephyr/sensorcommunity/',STR(?ROWNUM),'/observation/temperature/result')) AS ?results_URI)
    BIND (STRLANG(CONCAT('Result for observation of sensor: location: ','Aston University',' time: ',STR(?TimestampLocal),'property: pm10'),"en") AS ?result_label)	
    BIND (URI('http://qudt.org/vocab/unit/MicroGM-PER-M3') AS ?uom)
}
### observation result 9
CONSTRUCT {
  ?results_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?814_Ambient_tempC_slotB ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?814_Ambient_tempC_slotB))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/zephyr/sensorcommunity/',STR(?ROWNUM),'/observation/temperature/result')) AS ?results_URI)
    BIND (STRLANG(CONCAT('Result for observation of sensor: location: ','Aston University',' time: ',STR(?TimestampLocal),'property: ambient temperature'),"en") AS ?result_label)	
    BIND (URI('http://qudt.org/vocab/unit/DEG_C') AS ?uom)
}
### observation result 10
CONSTRUCT {
  ?results_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?814_Ambient_humidityRH_slotB ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?814_Ambient_humidityRH_slotB))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/zephyr/sensorcommunity/',STR(?ROWNUM),'/observation/temperature/result')) AS ?results_URI)
    BIND (STRLANG(CONCAT('Result for observation of sensor:: location: ','Aston University',' time: ',STR(?TimestampLocal),'property: ambient humidity'),"en") AS ?result_label)	
    BIND (URI('http://qudt.org/vocab/unit/PERCENT_RH') AS ?uom)
}
### observation result 11
CONSTRUCT {
  ?results_URI a sosa:Result ;
  	rdfs:label ?result_label ;
	qudt:numericValue ?814_Ambient_pressurehPa_slotB ;
	qudt:unit ?uom ;
}  	
FROM <file:5865900_wasserstand_mw_21_12_2013.csv> 
WHERE {
    FILTER (BOUND(?814_Ambient_pressurehPa_slotB))
    BIND (URI(CONCAT('http://w3id.org/ad4gd/zephyr/sensorcommunity/',STR(?ROWNUM),'/observation/temperature/result')) AS ?results_URI)
    BIND (STRLANG(CONCAT('Result for observation of sensor:: location: ','Aston University',' time: ',STR(?TimestampLocal),'property: ambient pressure'),"en") AS ?result_label)	
    BIND (URI('http://qudt.org/vocab/unit/HectoPA') AS ?uom)
}