name: Update AD4GD pilot vocabularies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  download-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Download files
        run: |
          mkdir -p AD4GD-vocabularies
          
          P1_BASE=https://github.com/AD4GD/pilot-1-water-quality/raw/refs/heads/master/rainbow-data/generic/entailed/
          for P in properties sensor-manufacturers sensors ; do
            wget "${P1_BASE}${P}.ttl" -O "AD4GD-vocabularies/pilot-1-water-quality-${P}.ttl"
          done
          
          wget https://github.com/AD4GD/pilot-2-biodoversity/raw/refs/heads/master/rainbow-data/entailed/ebv-iadopt.ttl -O AD4GD-vocabularies/pilot-2-ebv.ttl
          
          P3_BASE=https://github.com/AD4GD/pilot-3-air-quality/raw/refs/heads/main/rainbow-data/generic/entailed/
          for P in procedures properties sensor-manufacturers sensor-platforms sensors ; do
            wget "${P3_BASE}${P}.ttl" -O "AD4GD-vocabularies/pilot-3-air-quality-${P}.ttl"
          done
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'AD4GD-vocabularies/**'
